version: '3'
services:
  app:
    build: .
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_HIKARI_USERNAME=user
      - SPRING_DATASOURCE_HIKARI_PASSWORD=password
      - SPRING_DATASOURCE_HIKARI_JDBCURL=jdbc:postgresql://db:5432/postgres
    ports:
      - 8080:8080
  db:
    image: postgres
    container_name: db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
volumes:
  postgres-data: